apiVersion: apps/v1
kind: Deployment
metadata:
  name: ltdevents
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app
          volumeMounts:
            - name: "client-tls"
              mountPath: "/var/strimzi-client"
              readOnly: True
            - name: "broker-tls"
              mountPath: "/var/strimzi-broker"
              readOnly: True
      volumes:
        # Mount the TLS secret created by KafkaUser
        - name: "client-tls"
          secret:
            secretName: kafkauser-ltdevents  # matches name of KafkaUser
        - name: "broker-tls"
          secret:
            secretName: "events-cluster-ca-cert" # matches name of Strimzi cluster cluster CA cert secret
