sudo: false
dist: xenial
language: python
matrix:
    include:
      # Use the Python 3.6 build for PyPI deployments and doc uploads
      - python: "3.7"
        env: LTD_SKIP_UPLOAD=false
install:
  - pip install -r docs/requirements.txt
script:
  - cd docs && make linkcheck && make html && cd ../
after_success:
  - 'ltd upload --product roundtable --travis --dir docs/_build/html'
env:
  global:
    - LTD_SKIP_UPLOAD=true  # disable doc deploys in regular test matrix
    # LTD Keeper credentials
    - secure: "Ki5fetCGpWrD/idgW9KhfKhQ21v4aCMlqKw0T4qeAUzlVM7TZb7Gcc+hCuE9NHu0YZaIG443vLyiBE/+leeZxbARtUheamxA7Ld0hcsaAAZuhtBRPhMl4DzM2vtQH/Gw96NjZVPB3V838kJNxi4NGnsO8YAEB96bA6jH3LA4uulQSPvV5oMmKRDZTAZm/g+BpD1eG3e6i77ndy0acRtJjYq3d7WoSF3AGhccz9gGXBHDK8op9t3k90MhSHxQQ1gZDs961B/Vv7ZZcwXXYNttvM/1JkmigtQpI/jPYvhv7WoGERPXOdYCstQM8Ypm2l8vaPlfuFSgtDPZPtXqmpAmVQBC6GhQe8E9r0XpjUK/2gDAyZZnw1x98gPe29G+OFM69i6U19ECeVvj4O2k9P9rE1iZCuIl9rCwZXFJd99C/YQgs272Le+jZG9S1dE7tPVuZEA6CpMasH2vLWeb9tUntk8fqfRoEVo/e3xxHRpnbry37C/fFrH7swicnhPx+ovsrctgm5l/2wbdm/d7JZ8GOdEyjadC8ptpP769TwOdxi2sP8gIiFRJU8Ae7R9+THhpY+xdqEaeys7eORWpJyks5eGza2ePjzD6i63Wkmk0zWxb7MiHFfCNbb5kasTOA+0JMyWibSTOclhunVbvSK421oB0PJ9bOxzwr4l+dJ3GgvI="
