apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keeper
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "keeper-letsencrypt"
spec:
  tls:
    - hosts:
      - keeper.lsst.codes
      secretName: keeper-ingress-tls
  rules:
    - host: keeper.lsst.codes
      http:
        paths:
          - path: /
            backend:
              serviceName: keeper
              servicePort: 8080
