apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  # Default policy allows read-only access.
  policy.default: role:readonly
  # Make members of the lsst-sqre/roundtable-ops team administrators
  policy.csv: |
      g, lsst-sqre:roundtable-ops, role:admin
