apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  repositories: |
    - url: https://github.com/argoproj/argocd-example-apps.git
    - url: https://github.com/lsst-sqre/roundtable.git
    - url: https://github.com/argoproj/argo-cd.git
