apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-crd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployments/cert-manager-crd
    repoURL: https://github.com/lsst-sqre/roundtable
    targetRevision: HEAD
