apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployments/cert-manager
    repoURL: https://github.com/lsst-sqre/roundtable
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
  ignoreDifferences:
    - group: "certmanager.k8s.io"
      kind: Certificate
      jsonPointers:
        - /spec/duration
