apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    # See https://docs.cert-manager.io/en/latest/getting-started/webhook.html#disabling-validation-on-the-cert-manager-namespace
    certmanager.k8s.io/disable-validation: true
spec:
  finalizers:
    - kubernetes
