apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployments/sealed-secrets
    repoURL: https://github.com/lsst-sqre/roundtable
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
