apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: events

nameSuffix: "-jsick"

commonLabels:
  app: templatebot-jsick

resources:
  - resources/templatebot-sealedsecret.yaml
  - github.com/lsst-sqre/templatebot.git//manifests/base?ref=tickets/DM-22100

patches:
  - patches/templatebot-configmap.yaml
  - patches/templatebot-deployment.yaml
