apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/nginx-ingress-ns.yaml
  - resources/cert-manager-ns.yaml
  - resources/argo-cd.yaml
  - resources/nginx-ingress.yaml
  - resources/cert-manager-crd.yaml
