apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Storage classes
  - resources/ssd-storageclass.yaml
  # Namespaces
  - resources/nginx-ingress-ns.yaml
  - resources/cert-manager-ns.yaml
  - resources/prometheus-ns.yaml
  - resources/strimzi-ns.yaml
  - resources/events-ns.yaml
  - resources/events-dev-ns.yaml
  - resources/sealed-secrets-ns.yaml
  # Applications
  - resources/argo-cd.yaml
  - resources/nginx-ingress.yaml
  - resources/cert-manager-crd.yaml
  # - resources/cert-manager.yaml  # disabled for upgrade to 0.6
  - resources/prometheus.yaml
  - resources/strimzi.yaml
  - resources/events-dev.yaml
  - resources/events.yaml
  - resources/sealed-secrets.yaml
