apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: events-dev
spec:
  kafka:
    version: 2.3.0
    replicas: 1
    resources:
      requests:
        memory: 1Gi
        cpu: "300m"
      limits:
        memory: 3Gi
        cpu: "1"
    template:
      persistentVolumeClaim:
        metadata:
          annotations:
            # https://argoproj.github.io/argo-cd/user-guide/compare-options/
            argocd.argoproj.io/compare-options: IgnoreExtraneous
    # https://strimzi.io/docs/latest/#ref-jvm-options-deployment-configuration-kafka
    # The recommendation is to keep the minimum (Xms) the same as the maximum
    # (Xmx). Expect the usage to be 4.5x this value; hence the 3 to 4 Gi
    # Kubernetes limit.
    jvmOptions:
      -Xms: 512M
      -Xmx: 512M
    listeners:
      # Enable the TLS listener (encrypted) on 9093 with mutual TLS
      # authentication
      # https://strimzi.io/docs/latest/#assembly-kafka-broker-listener-authentication-deployment-configuration-kafka
      tls:
        authentication:
          type: tls
      # Enable an unencrypted and unauthenticated listener on port 9092
      # for debugging
      plain: {}
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.3"
    storage:
      type: ephemeral
    metrics:
      lowercaseOutputName: true
  zookeeper:
    replicas: 1
    resources:
      requests:
        memory: 1Gi
        cpu: "300m"
      limits:
        memory: 3Gi
        cpu: "1"
    template:
      persistentVolumeClaim:
        metadata:
          annotations:
            # https://argoproj.github.io/argo-cd/user-guide/compare-options/
            argocd.argoproj.io/compare-options: IgnoreExtraneous
    # https://strimzi.io/docs/latest/#ref-jvm-options-deployment-configuration-kafka
    jvmOptions:
      -Xms: 512M
      -Xmx: 512M
    storage:
      type: ephemeral
  entityOperator:
    topicOperator:
      watchedNamespace: events-dev
    userOperator:
      watchedNamespace: events-dev
