apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: events

images:
  - name: lsstsqre/safirdemo
    newTag: tickets-DM-23356-docker-build

resources:
  - github.com/lsst-sqre/safirdemo.git//manifests/base?ref=tickets/DM-23356-docker-build
