apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: events

images:
  - name: lsstsqre/checkerboard
    newTag: tickets-DM-23590

resources:
  - github.com/lsst-sqre/checkerboard.git//manifests/base?ref=tickets/DM-23590
  - resources/secret.yaml
