apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/kafka.yaml
  # Kafka topics
  - resources/schemas-topic.yaml
  # Kafka users
  - resources/demo-user.yaml
  - resources/schemaregistry-user.yaml

namespace: events
