apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/kafka.yaml
  # Schema Registry
  - resources/schema-registry-user.yaml
  - github.com/lsst-sqre/strimzi-registry-operator.git//manifests?refs=0.1.0
  - resources/schemas-topic.yaml
  # Kafka topics
  # TODO
  # Kafka users
  - resources/demo-user.yaml

namespace: events
