apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    # See https://docs.cert-manager.io/en/latest/getting-started/webhook.html#disabling-validation-on-the-cert-manager-namespace
    certmanager.k8s.io/disable-validation: "true"
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-crd
  annotations:
    # Sync these CRDs before other applications (particularly cert-manager itself).
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployments/cert-manager-crd
    repoURL: https://github.com/lsst-sqre/roundtable
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployments/cert-manager
    repoURL: https://github.com/lsst-sqre/roundtable
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
  ignoreDifferences:
    - group: "certmanager.k8s.io"
      kind: Certificate
      jsonPointers:
        - /spec/duration
