prometheus-operator:
  prometheusOperator:
    admissionWebhooks:
      enabled: false
    tlsProxy:
      enabled: false
  grafana:
    sidecar:
      dashboards:
        enabled: true
        label: "grafana_dashboard"
        searchNamespace: "ALL"
