apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v1.2.0

patchesStrategicMerge:
- patches/repositories.yaml
- patches/helm-repositories.yaml

# Adds the argocd namespace to all resources, which is required anyhow.
namespace: argocd
