apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sqrbot-jsick
spec:
  destination:
    namespace: sqrbot-jsick
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployments/sqrbot-jsick
    repoURL: https://github.com/lsst-sqre/roundtable
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
