apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: argocd-grpc-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sqre-admin@lists.lsst.org
    privateKeySecretRef:
      name: argocd-grpc-letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
